language: python
python:
  - "3.7"
install:
  - pip install pygments lxml setuptools --upgrade
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update
script:
  - bikeshed spec index.bs index.html
  - bash ./deploy.sh
env:
  global:
  # Fingerprint: d2:fe:98:79:00:b4:58:d0:ff:d2:10:59:68:ea:60:0a
  - ENCRYPTION_LABEL: "9f1a8190f26b"
  - COMMIT_AUTHOR_EMAIL: "miguelecasassanchez@gmail.com"
